In [1]:
import re
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup
import urllib

import pandas as pd

In [2]:
team = pd.read_csv("2020빅콘테스트_스포츠투아이_제공데이터_팀_2020.csv", engine = 'python')

In [3]:
tmp1 = list(team.T_NM)
tmp2 = list(team.T_ID)

team_dict = dict()

for i in range(len(tmp1)):
    team_dict[tmp1[i]] = tmp2[i]
team_dict

{'한화': 'HH',
 'KIA': 'HT',
 'KT': 'KT',
 'LG': 'LG',
 '롯데': 'LT',
 'NC': 'NC',
 '두산': 'OB',
 'SK': 'SK',
 '삼성': 'SS',
 '키움': 'WO'}

### 1. 함수

In [4]:
def read_txt(file_name):

    # 날짜 데이터 읽기
    f = open(file_name, mode = 'r')
    f_urls = f.readlines()
    urls = f_urls[0][1:-1].split(',')
    return urls

In [5]:
def make_dataframe(file_name):
    
    col_lst = ['GDAY_DS','T_ID']
    
    if file_name == '득점권_투수2.txt':
        col_lst.append('WHIP')
    elif file_name == '득점권_타자2.txt':
        col_lst.append('득점권_타율')

    # dataframe
    data = pd.DataFrame([],columns = col_lst)

    return data

In [6]:
def create_row(data, urls, num):
    idx = 0
    for url in urls:
        url = url.strip()[1:-1]

        # 날짜
        day_lst = url.split('&')[28].split('=')[1].split('-')
        day = '2020{}{}'.format(day_lst[0],day_lst[1])
        print("=====",day)

        fp = urlopen(url)
        source = fp.read()
        fp.close()

        soup = BeautifulSoup(source)

        table = soup.find(id='mytable')
        trs = table.find_all('tr')  

        for i in range(3,len(trs)):
            tmp = trs[i].text.split()

            for t in team_dict:
                if t in tmp[0]:
                    t_id = team_dict[t]
                    break

            row = [day, t_id]
            
            value = tmp[num]

            row.append(value)
            
            print("ROW",value, row)

            data.loc[idx,:] = row
            idx += 1

    return data

### 2. 함수사용

#### 1) 득점권 투수

In [7]:
file_name = '득점권_투수2.txt' # file 명 따라 수정
urls = read_txt(file_name)
pp_data = make_dataframe(file_name)
sco_p2020 = create_row(pp_data, urls, -5)

===== 20200922
ROW 7.00 ['20200922', 'KT', '7.00']
ROW 3.00 ['20200922', 'OB', '3.00']
ROW 1.67 ['20200922', 'SK', '1.67']
ROW 1.50 ['20200922', 'NC', '1.50']
ROW 1.50 ['20200922', 'LG', '1.50']
ROW 1.00 ['20200922', 'HT', '1.00']
ROW 0.00 ['20200922', 'WO', '0.00']
ROW 0.00 ['20200922', 'HH', '0.00']
ROW 0.60 ['20200922', 'SS', '0.60']
ROW 0.00 ['20200922', 'LT', '0.00']
===== 20200923
ROW 3.75 ['20200923', 'SS', '3.75']
ROW 3.00 ['20200923', 'SK', '3.00']
ROW 2.75 ['20200923', 'HT', '2.75']
ROW 2.00 ['20200923', 'NC', '2.00']
ROW 2.46 ['20200923', 'LT', '2.46']
ROW 2.00 ['20200923', 'KT', '2.00']
ROW 0.82 ['20200923', 'OB', '0.82']
ROW 1.20 ['20200923', 'HH', '1.20']
ROW 0.43 ['20200923', 'LG', '0.43']
ROW 0.00 ['20200923', 'WO', '0.00']
===== 20200924
ROW 3.00 ['20200924', 'NC', '3.00']
ROW 2.25 ['20200924', 'LG', '2.25']
ROW 1.20 ['20200924', 'SK', '1.20']
ROW 1.80 ['20200924', 'LT', '1.80']
ROW 1.64 ['20200924', 'KT', '1.64']
ROW 1.13 ['20200924', 'HT', '1.13']
ROW 1.67 ['20200924', 'HH', '1.67']
ROW 1.50 ['20200924', 'WO', '1.50']
ROW 1.00 ['20200924', 'SS', '1.00']
ROW 1.00 ['20200924', 'OB', '1.00']
===== 20200925
ROW 1.88 ['20200925', 'HT', '1.88']
ROW 1.00 ['20200925', 'SS', '1.00']
ROW 1.60 ['20200925', 'WO', '1.60']
ROW 1.60 ['20200925', 'SK', '1.60']
ROW 1.00 ['20200925', 'KT', '1.00']
ROW 2.00 ['20200925', 'OB', '2.00']
ROW 0.86 ['20200925', 'HH', '0.86']
ROW 1.09 ['20200925', 'LG', '1.09']
ROW 1.67 ['20200925', 'LT', '1.67']
ROW 0.43 ['20200925', 'NC', '0.43']
===== 20200926
ROW 4.71 ['20200926', 'HH', '4.71']
ROW 4.33 ['20200926', 'HT', '4.33']
ROW 1.88 ['20200926', 'SK', '1.88']
ROW 2.00 ['20200926', 'WO', '2.00']
ROW 2.00 ['20200926', 'KT', '2.00']
ROW 0.55 ['20200926', 'LT', '0.55']
ROW 1.80 ['20200926', 'LG', '1.80']
ROW 2.40 ['20200926', 'SS', '2.40']
ROW 0.00 ['20200926', 'NC', '0.00']
ROW 1.00 ['20200926', 'OB', '1.00']
===== 20200927
===== 20200929

In [8]:
sco_p2020

     GDAY_DS T_ID  WHIP
0   20200922   KT  7.00
1   20200922   OB  3.00
2   20200922   SK  1.67
3   20200922   NC  1.50
4   20200922   LG  1.50
5   20200922   HT  1.00
6   20200922   WO  0.00
7   20200922   HH  0.00
8   20200922   SS  0.60
9   20200922   LT  0.00
10  20200923   SS  3.75
11  20200923   SK  3.00
12  20200923   HT  2.75
13  20200923   NC  2.00
14  20200923   LT  2.46
15  20200923   KT  2.00
16  20200923   OB  0.82
17  20200923   HH  1.20
18  20200923   LG  0.43
19  20200923   WO  0.00
20  20200924   NC  3.00
21  20200924   LG  2.25
22  20200924   SK  1.20
23  20200924   LT  1.80
24  20200924   KT  1.64
25  20200924   HT  1.13
26  20200924   HH  1.67
27  20200924   WO  1.50
28  20200924   SS  1.00
29  20200924   OB  1.00
30  20200925   HT  1.88
31  20200925   SS  1.00
32  20200925   WO  1.60
33  20200925   SK  1.60
34  20200925   KT  1.00
35  20200925   OB  2.00
36  20200925   HH  0.86
37  20200925   LG  1.09
38  20200925   LT  1.67
39  20200925   NC  0.43
40  20200926   HH  4.71
41  20200926   HT  4.33
42  20200926   SK  1.88
43  20200926   WO  2.00
44  20200926   KT  2.00
45  20200926   LT  0.55
46  20200926   LG  1.80
47  20200926   SS  2.40
48  20200926   NC  0.00
49  20200926   OB  1.00

In [9]:
sco_p2020_fill = sco_p2020.fillna(0)

In [10]:
ppp = pd.read_csv("pitcher2020_2.csv")
ppp['GDAY_DS'] = ppp['GDAY_DS'].astype(str)
tt = pd.merge(ppp, sco_p2020, how = 'left', left_on = ['GDAY_DS','T_ID'], right_on = ['GDAY_DS','T_ID'])
tt[tt["WHIP"].isnull()]

Empty DataFrame
Columns: [GDAY_DS, T_ID, 출장, 선발, 완투, 완봉, 승, 패, 홀드, 세, 이닝, 실점, 자책, 타자, 타수, 안타, 2타, 3타, 홈런, 볼넷, 고4, 사구, 삼진, 투구, WHIP]
Index: []

[0 rows x 25 columns]

In [11]:
save_pp = pd.merge(ppp, sco_p2020_fill, how = 'left', left_on = ['GDAY_DS','T_ID'], right_on = ['GDAY_DS','T_ID']).sort_values(by = ["GDAY_DS","T_ID"]).reset_index(drop=True)
save_pp

,GDAY_DS,T_ID,출장,선발,완투,완봉,승,패,홀드,세,...,안타,2타,3타,홈런,볼넷,고4,사구,삼진,투구,WHIP
0,20200922,HH,4,1,0,0,1,0,2,0,...,6,0,0,1,3,0,1,5,125,0.00
1,20200922,HT,4,1,0,0,0,1,0,0,...,5,1,0,0,3,0,0,3,131,1.00
2,20200922,KT,4,1,0,0,0,1,0,0,...,10,0,0,2,5,2,0,5,130,7.00
3,20200922,LG,4,1,0,0,1,0,1,1,...,3,0,0,1,1,0,0,9,141,1.50
4,20200922,LT,3,1,0,0,1,0,0,0,...,2,0,0,0,2,0,0,10,122,0.00
5,20200922,NC,4,1,0,0,1,0,0,1,...,6,0,0,0,1,0,0,11,146,1.50
6,20200922,OB,4,1,0,0,0,1,0,0,...,6,0,0,1,4,0,1,16,145,3.00
7,20200922,SK,4,1,0,0,0,1,0,0,...,7,1,0,0,5,0,0,5,149,1.67
8,20200922,SS,6,1,0,0,0,1,3,0,...,6,1,0,0,4,0,2,4,155,0.60
9,20200922,WO,3,1,0,0,1,0,1,1,...,4,0,0,0,3,0,0,8,131,0.00
10,20200923,HH,6,1,0,0,1,0,3,1,...,11,5,0,0,5,0,0,6,165,1.20
11,20200923,HT,4,1,0,0,0,1,0,0,...,17,3,2,2,4,0,1,6,159,2.75
12,20200923,KT,6,1,0,0,1,0,2,0,...,9,1,0,1,8,0,0,7,170,2.00
13,20200923,LG,3,1,0,0,1,0,1,0,...,8,3,0,0,1,0,0,10,138,0.43
14,20200923,LT,6,1,0,0,0,1,0,0,...,16,3,0,1,3,0,1,5,167,2.46
15,20200923,NC,5,1,0,0,1,0,0,1,...,10,2,1,1,2,0,0,11,143,2.00
16,20200923,OB,5,1,0,0,0,1,0,0,...,12,3,0,1,2,0,1,13,159,0.82
17,20200923,SK,3,1,0,0,0,1,0,0,...,10,2,0,1,1,0,0,6,145,3.00
18,20200923,SS,6,1,0,0,0,1,0,0,...,10,1,0,1,5,0,0,7,143,3.75
19,20200923,WO,4,1,0,0,1,0,0,0,...,5,0,0,1,1,0,1,7,133,0.00
20,20200924,HH,4,1,0,0,1,0,0,1,...,6,0,0,0,5,0,0,5,156,1.67
21,20200924,HT,5,1,0,0,1,0,1,1,...,8,2,0,0,3,0,0,11,154,1.13
22,20200924,KT,7,1,0,0,0,1,0,0,...,16,4,1,0,5,0,0,3,187,1.64
23,20200924,LG,6,1,0,0,0,1,1,0,...,17,4,0,2,3,0,2,4,193,2.25
24,20200924,LT,6,1,0,0,0,1,0,0,...,15,4,0,1,3,1,1,8,144,1.80
25,20200924,NC,6,1,0,0,1,0,0,0,...,9,1,0,4,7,0,0,11,169,3.00
26,20200924,OB,3,1,0,0,1,0,0,1,...,7,1,0,0,2,0,0,8,132,1.00
27,20200924,SK,4,1,0,0,0,1,0,0,...,9,1,0,0,2,0,1,7,122,1.20
28,20200924,SS,4,1,0,0,0,1,0,0,...,1,0,0,0,5,1,1,5,130,1.00
29,20200924,WO,3,1,0,0,1,0,0,0,...,6,1,0,0,4,0,0,8,125,1.50
30,20200925,HH,6,1,0,0,1,0,0,0,...,13,0,0,2,3,0,1,6,177,0.86
31,20200925,HT,5,1,0,0,0,1,0,0,...,12,1,0,2,7,0,0,1,150,1.88
32,20200925,KT,3,1,0,0,1,0,1,1,...,12,2,0,0,3,0,0,4,159,1.00
33,20200925,LG,4,1,0,0,0,1,0,0,...,9,2,1,1,6,0,3,10,172,1.09
34,20200925,LT,7,1,0,0,0,1,2,0,...,13,2,0,3,6,1,1,7,158,1.67
35,20200925,NC,4,1,0,0,1,0,0,0,...,7,0,0,1,3,0,0,7,132,0.43
36,20200925,OB,4,1,0,0,0,1,0,0,...,7,0,0,1,2,0,0,7,131,2.00
37,20200925,SK,7,1,0,0,1,0,0,0,...,17,4,0,0,4,0,0,11,195,1.60
38,20200925,SS,4,1,0,0,1,0,2,1,...,7,1,1,0,2,0,0,6,133,1.00
39,20200925,WO,10,1,0,0,0,1,0,0,...,10,3,0,1,7,2,0,6,173,1.60
40,20200926,HH,5,1,0,0,0,1,0,0,...,16,1,1,2,9,0,0,7,223,4.71
41,20200926,HT,3,1,0,0,0,1,0,0,...,18,7,0,1,4,0,1,5,174,4.33
42,20200926,KT,8,1,0,0,0,1,0,0,...,7,1,1,0,6,0,0,3,142,2.00
43,20200926,LG,7,1,0,0,1,0,0,1,...,7,2,0,0,4,0,0,5,157,1.80
44,20200926,LT,5,1,0,0,1,0,0,0,...,8,1,0,0,5,0,1,7,163,0.55
45,20200926,NC,3,1,0,0,1,0,0,0,...,9,2,0,1,1,0,0,7,130,0.00
46,20200926,OB,3,1,0,0,1,0,0,0,...,3,1,0,0,2,0,0,9,127,1.00
47,20200926,SK,5,1,0,0,0,1,0,0,...,12,1,0,3,4,0,0,3,148,1.88
48,20200926,SS,3,1,0,0,1,0,0,0,...,8,0,0,1,2,0,0,10,145,2.40
49,20200926,WO,3,1,0,0,0,1,0,0,...,9,2,1,0,2,0,0,3,113,2.00

In [12]:
save_pp.to_csv("0920_total_pitcher_2.csv",index=False)

#### 4) 득점권 타자

In [13]:
file_name = '득점권_타자2.txt' # file 명 따라 수정
urls = read_txt(file_name)
hh_data = make_dataframe(file_name)
sco_h2020 = create_row(hh_data, urls, -4)

===== 20200922
ROW .600 ['20200922', 'LT', '.600']
ROW .429 ['20200922', 'HH', '.429']
ROW .333 ['20200922', 'SK', '.333']
ROW .333 ['20200922', 'LG', '.333']
ROW .333 ['20200922', 'SS', '.333']
ROW .200 ['20200922', 'WO', '.200']
ROW .143 ['20200922', 'NC', '.143']
ROW .000 ['20200922', 'OB', '.000']
ROW .000 ['20200922', 'KT', '.000']
ROW .000 ['20200922', 'HT', '.000']
===== 20200923
ROW .625 ['20200923', 'NC', '.625']
ROW .500 ['20200923', 'LG', '.500']
ROW .500 ['20200923', 'WO', '.500']
ROW .353 ['20200923', 'KT', '.353']
ROW .286 ['20200923', 'SS', '.286']
ROW .231 ['20200923', 'HH', '.231']
ROW .176 ['20200923', 'OB', '.176']
ROW .000 ['20200923', 'LT', '.000']
ROW .000 ['20200923', 'SK', '.000']
ROW .000 ['20200923', 'HT', '.000']
===== 20200924
ROW .500 ['20200924', 'NC', '.500']
ROW .400 ['20200924', 'LG', '.400']
ROW .333 ['20200924', 'HH', '.333']
ROW .313 ['20200924', 'HT', '.313']
ROW .308 ['20200924', 'WO', '.308']
ROW .300 ['20200924', 'LT', '.300']
ROW .222 ['20200924', 'KT', '.222']
ROW .200 ['20200924', 'SK', '.200']
ROW .100 ['20200924', 'OB', '.100']
ROW .000 ['20200924', 'SS', '.000']
===== 20200925
ROW .400 ['20200925', 'KT', '.400']
ROW .368 ['20200925', 'WO', '.368']
ROW .286 ['20200925', 'LT', '.286']
ROW .250 ['20200925', 'SS', '.250']
ROW .200 ['20200925', 'HH', '.200']
ROW .200 ['20200925', 'HT', '.200']
ROW .188 ['20200925', 'SK', '.188']
ROW .167 ['20200925', 'OB', '.167']
ROW .100 ['20200925', 'NC', '.100']
ROW .000 ['20200925', 'LG', '.000']
===== 20200926
ROW .556 ['20200926', 'LT', '.556']
ROW .500 ['20200926', 'NC', '.500']
ROW .400 ['20200926', 'OB', '.400']
ROW .300 ['20200926', 'SS', '.300']
ROW .286 ['20200926', 'SK', '.286']
ROW .273 ['20200926', 'LG', '.273']
ROW .200 ['20200926', 'KT', '.200']
ROW .167 ['20200926', 'HT', '.167']
ROW .000 ['20200926', 'HH', '.000']
ROW .000 ['20200926', 'WO', '.000']
===== 20200927
===== 20200929

In [14]:
sco_h2020

     GDAY_DS T_ID 득점권_타율
0   20200922   LT   .600
1   20200922   HH   .429
2   20200922   SK   .333
3   20200922   LG   .333
4   20200922   SS   .333
5   20200922   WO   .200
6   20200922   NC   .143
7   20200922   OB   .000
8   20200922   KT   .000
9   20200922   HT   .000
10  20200923   NC   .625
11  20200923   LG   .500
12  20200923   WO   .500
13  20200923   KT   .353
14  20200923   SS   .286
15  20200923   HH   .231
16  20200923   OB   .176
17  20200923   LT   .000
18  20200923   SK   .000
19  20200923   HT   .000
20  20200924   NC   .500
21  20200924   LG   .400
22  20200924   HH   .333
23  20200924   HT   .313
24  20200924   WO   .308
25  20200924   LT   .300
26  20200924   KT   .222
27  20200924   SK   .200
28  20200924   OB   .100
29  20200924   SS   .000
30  20200925   KT   .400
31  20200925   WO   .368
32  20200925   LT   .286
33  20200925   SS   .250
34  20200925   HH   .200
35  20200925   HT   .200
36  20200925   SK   .188
37  20200925   OB   .167
38  20200925   NC   .100
39  20200925   LG   .000
40  20200926   LT   .556
41  20200926   NC   .500
42  20200926   OB   .400
43  20200926   SS   .300
44  20200926   SK   .286
45  20200926   LG   .273
46  20200926   KT   .200
47  20200926   HT   .167
48  20200926   HH   .000
49  20200926   WO   .000

In [15]:
hhh = pd.read_csv("hitter2020_2.csv")
hhh['GDAY_DS'] = hhh['GDAY_DS'].astype(str)
tt = pd.merge(hhh, sco_h2020, how = 'left', left_on = ['GDAY_DS','T_ID'], right_on = ['GDAY_DS','T_ID'])
tt[tt["득점권_타율"].isnull()]

Empty DataFrame
Columns: [GDAY_DS, T_ID, 타석, 타수, 득점, 안타, 2타, 3타, 홈런, 루타, 타점, 도루, 도실, 볼넷, 사구, 고4, 삼진, 병살, 희타, 희비, 득점권_타율]
Index: []

[0 rows x 21 columns]

In [16]:
sco_h2020_fill = sco_h2020.fillna(0)

In [17]:
save_hh = pd.merge(hhh, sco_h2020_fill, how = 'left', left_on = ['GDAY_DS','T_ID'], right_on = ['GDAY_DS','T_ID']).sort_values(by = ["GDAY_DS","T_ID"]).reset_index(drop=True)
save_hh

,GDAY_DS,T_ID,타석,타수,득점,안타,2타,3타,홈런,루타,...,도루,도실,볼넷,사구,고4,삼진,병살,희타,희비,득점권_타율
0,20200922,HH,35,29,5,6,0,0,1,9,...,0,0,4,1,0,16,0,1,0,.429
1,20200922,HT,33,30,0,4,0,0,0,4,...,0,0,3,0,0,8,1,0,0,.000
2,20200922,KT,30,28,0,2,0,0,0,2,...,0,1,2,0,0,10,0,0,0,.000
3,20200922,LG,35,30,7,7,1,0,0,8,...,2,0,5,0,0,5,2,0,0,.333
4,20200922,LT,36,31,8,10,0,0,2,16,...,1,0,5,0,2,5,2,0,0,.600
5,20200922,NC,36,30,3,6,1,0,0,7,...,1,0,4,2,0,4,1,0,0,.143
6,20200922,OB,33,29,1,6,0,0,1,9,...,0,0,3,1,0,5,3,0,0,.000
7,20200922,SK,32,31,2,3,0,0,1,6,...,1,0,1,0,0,9,0,0,0,.333
8,20200922,SS,34,33,2,6,0,0,0,6,...,0,0,1,0,0,11,0,0,0,.333
9,20200922,WO,35,32,2,5,1,0,0,6,...,0,0,3,0,0,3,0,0,0,.200
10,20200923,HH,38,34,6,12,3,0,1,18,...,1,0,2,1,0,13,1,1,0,.231
11,20200923,HT,34,32,1,5,0,0,1,8,...,0,0,1,1,0,7,0,0,0,.000
12,20200923,KT,46,42,10,16,3,0,1,22,...,1,1,3,1,0,5,0,0,0,.353
13,20200923,LG,33,31,6,10,2,0,1,15,...,0,1,1,0,0,6,0,0,1,.500
14,20200923,LT,41,33,5,9,1,0,1,13,...,0,0,8,0,0,7,3,0,0,.000
15,20200923,NC,36,30,8,10,1,0,1,14,...,0,1,5,0,0,7,2,0,1,.625
16,20200923,OB,43,37,5,11,5,0,0,16,...,0,0,5,0,0,6,0,0,1,.176
17,20200923,SK,36,33,2,8,3,0,0,11,...,0,0,1,0,0,10,0,0,2,.000
18,20200923,SS,39,36,7,10,2,1,1,17,...,2,0,2,0,0,11,0,0,1,.286
19,20200923,WO,48,42,13,17,3,2,2,30,...,0,0,4,1,0,6,1,0,1,.500
20,20200924,HH,41,36,7,15,4,0,1,22,...,2,1,3,1,1,8,2,1,0,.333
21,20200924,HT,46,40,5,16,4,1,0,22,...,0,0,5,0,0,3,1,1,0,.313
22,20200924,KT,37,34,3,8,2,0,0,10,...,0,0,3,0,0,11,0,0,0,.222
23,20200924,LG,42,35,8,9,1,0,4,22,...,1,0,7,0,0,11,1,0,0,.400
24,20200924,LT,38,32,4,6,0,0,0,6,...,3,0,5,0,0,5,1,0,1,.300
25,20200924,NC,45,39,12,17,4,0,2,27,...,0,0,3,2,0,4,1,0,1,.500
26,20200924,OB,33,26,1,1,0,0,0,1,...,0,0,5,1,1,5,0,1,0,.100
27,20200924,SK,33,29,1,6,1,0,0,7,...,1,1,4,0,0,8,3,0,0,.200
28,20200924,SS,34,32,0,7,1,0,0,8,...,1,0,2,0,0,8,2,0,0,.000
29,20200924,WO,36,32,6,9,1,0,0,10,...,2,0,2,1,0,7,0,0,1,.308
30,20200925,HH,48,40,6,13,2,0,3,24,...,0,0,6,1,1,7,1,1,0,.200
31,20200925,HT,40,37,3,12,2,0,0,14,...,0,0,3,0,0,4,1,0,0,.200
32,20200925,KT,40,31,7,12,1,0,2,19,...,1,1,7,0,0,1,2,1,1,.400
33,20200925,LG,36,33,1,7,0,0,1,10,...,0,0,3,0,0,7,1,0,0,.000
34,20200925,LT,42,37,5,13,0,0,2,19,...,0,0,3,1,0,6,3,0,1,.286
35,20200925,NC,42,30,7,9,2,1,1,16,...,2,0,6,3,0,10,1,1,2,.100
36,20200925,OB,36,32,3,7,1,1,0,10,...,0,0,2,0,0,6,0,1,1,.167
37,20200925,SK,48,40,8,10,3,0,1,16,...,7,0,7,0,2,6,1,1,0,.188
38,20200925,SS,34,31,4,7,0,0,1,10,...,2,0,2,0,0,7,1,1,0,.250
39,20200925,WO,50,45,6,17,4,0,0,21,...,2,1,4,0,0,11,1,1,0,.368
40,20200926,HH,37,36,1,9,2,0,1,14,...,0,0,1,0,0,7,0,0,0,.000
41,20200926,HT,40,34,3,8,1,0,0,9,...,0,0,5,1,0,7,2,0,0,.167
42,20200926,KT,36,31,1,7,2,0,0,9,...,2,1,4,0,0,5,0,0,1,.200
43,20200926,LG,39,31,3,7,1,1,0,10,...,1,0,6,0,0,3,1,2,0,.273
44,20200926,LT,50,44,16,18,7,0,1,28,...,0,0,4,1,0,5,0,0,1,.556
45,20200926,NC,51,42,13,16,1,1,2,25,...,0,1,9,0,0,7,0,0,0,.500
46,20200926,OB,35,31,4,9,2,1,0,13,...,0,0,2,0,0,3,0,2,0,.400
47,20200926,SK,36,32,2,8,0,0,1,11,...,0,1,2,0,0,10,0,2,0,.286
48,20200926,SS,38,33,8,12,1,0,3,22,...,0,0,4,0,0,3,2,1,0,.300
49,20200926,WO,32,30,0,3,1,0,0,4,...,1,0,2,0,0,9,0,0,0,.000

In [18]:
save_hh.to_csv("0920_total_hitter_2.csv",index=False)